# Generated by Django 5.2.8 on 2026-03-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_widget_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
