# Generated by Django 5.2.8 on 2026-03-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_link_url_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='icon_url',
        ),
    ]
