# Generated by Django 5.2.8 on 2026-03-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_link_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='is_wide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('list', 'Liste de liens'), ('note', 'Bloc-notes'), ('command', 'Lanceur de scripts'), ('snippet', 'Bloc de commandes')], default='list', max_length=10),
        ),
    ]
