# Generated by Django 5.2.8 on 2026-05-11 01:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_widget_is_wide_snippet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_title', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=500)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dashboard.link')),
                ('widget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_logs', to='dashboard.widget')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
