"""
Django settings for startme project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import mimetypes
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Charge les variables d'environnement depuis le fichier .env
load_dotenv()

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/javascript", ".js", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Défaut sécurisé : False. Activer DEBUG=True dans .env uniquement en développement.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Aucune clé en dur : elle doit venir du .env. En dev, une clé jetable est
# tolérée ; hors DEBUG, l'absence de clé fait échouer le démarrage volontairement.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-key-uniquement-pour-le-developpement'
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY est absent. Définissez-le dans votre fichier .env "
            "(voir .env.example)."
        )

# Défaut restrictif : l'app n'écoute que localhost. Élargir via ALLOWED_HOSTS
# dans .env seulement si un accès réseau est réellement souhaité.
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Disques surveillés par le widget système — format : "Nom:/chemin|Nom:/chemin"
_raw_disks = os.getenv('MONITOR_DISKS', 'Système:/')
MONITOR_DISKS = [
    {'name': part.split(':')[0], 'path': part.split(':')[1]}
    for part in _raw_disks.split('|')
    if ':' in part
]

# Widget Météo
WEATHER_CITY = os.getenv('WEATHER_CITY', 'Montréal, QC')
WEATHER_LAT = os.getenv('WEATHER_LAT', '45.5017')
WEATHER_LON = os.getenv('WEATHER_LON', '-73.5673')
WEATHER_TIMEZONE = os.getenv('WEATHER_TIMEZONE', 'America/Toronto')

# Widget Horloges — format : "Label:Timezone/IANA|Label:Timezone/IANA"
_raw_clocks = os.getenv('CLOCK_TIMEZONES', 'Paris:Europe/Paris|SF:America/Los_Angeles|Pékin:Asia/Shanghai')
CLOCK_TIMEZONES = [
    {'label': part.split(':')[0], 'timezone': ':'.join(part.split(':')[1:])}
    for part in _raw_clocks.split('|')
    if ':' in part
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'dashboard',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Exige une session authentifiée pour TOUTES les vues par défaut.
    # Doit être placé après AuthenticationMiddleware. Les exceptions se
    # déclarent avec @login_not_required (cf. la vue de login dans urls.py).
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

# Authentification — où rediriger et où atterrir
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

ROOT_URLCONF = 'startme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'startme.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Fuseau local pour l'AFFICHAGE des horodatages (ex. historique de commandes).
# Le stockage en base reste en UTC grâce à USE_TZ = True.
TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Journalisation : sortie console uniquement (suffisant pour une app locale).
# Sans ce bloc, les logger.debug(...) de dashboard/views.py sont invisibles.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {name} : {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # En développement, on veut voir les logger.debug du code applicatif.
        # Le logger 'dashboard' n'a pas de handler propre : il propage vers
        # le handler console de root.
        'dashboard': {
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}
